/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { X3dhKeyBundleResponse } from '../models';
// @ts-ignore
import type { X3dhKeyBundleUploadRequest } from '../models';
/**
 * PkiControllerApi - axios parameter creator
 * @export
 */
export const PkiControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} username 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getKeyBundle: async (username: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'username' is not null or undefined
            assertParamExists('getKeyBundle', 'username', username)
            const localVarPath = `/pki/key-bundle`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (username !== undefined) {
                localVarQueryParameter['username'] = username;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {X3dhKeyBundleUploadRequest} x3dhKeyBundleUploadRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadKeyBundle: async (x3dhKeyBundleUploadRequest: X3dhKeyBundleUploadRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'x3dhKeyBundleUploadRequest' is not null or undefined
            assertParamExists('uploadKeyBundle', 'x3dhKeyBundleUploadRequest', x3dhKeyBundleUploadRequest)
            const localVarPath = `/pki/upload/key-bundle`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(x3dhKeyBundleUploadRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PkiControllerApi - functional programming interface
 * @export
 */
export const PkiControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PkiControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} username 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getKeyBundle(username: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<X3dhKeyBundleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getKeyBundle(username, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PkiControllerApi.getKeyBundle']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {X3dhKeyBundleUploadRequest} x3dhKeyBundleUploadRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadKeyBundle(x3dhKeyBundleUploadRequest: X3dhKeyBundleUploadRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadKeyBundle(x3dhKeyBundleUploadRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PkiControllerApi.uploadKeyBundle']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PkiControllerApi - factory interface
 * @export
 */
export const PkiControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PkiControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {string} username 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getKeyBundle(username: string, options?: RawAxiosRequestConfig): AxiosPromise<X3dhKeyBundleResponse> {
            return localVarFp.getKeyBundle(username, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {X3dhKeyBundleUploadRequest} x3dhKeyBundleUploadRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadKeyBundle(x3dhKeyBundleUploadRequest: X3dhKeyBundleUploadRequest, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.uploadKeyBundle(x3dhKeyBundleUploadRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PkiControllerApi - object-oriented interface
 * @export
 * @class PkiControllerApi
 * @extends {BaseAPI}
 */
export class PkiControllerApi extends BaseAPI {
    /**
     * 
     * @param {string} username 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PkiControllerApi
     */
    public getKeyBundle(username: string, options?: RawAxiosRequestConfig) {
        return PkiControllerApiFp(this.configuration).getKeyBundle(username, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {X3dhKeyBundleUploadRequest} x3dhKeyBundleUploadRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PkiControllerApi
     */
    public uploadKeyBundle(x3dhKeyBundleUploadRequest: X3dhKeyBundleUploadRequest, options?: RawAxiosRequestConfig) {
        return PkiControllerApiFp(this.configuration).uploadKeyBundle(x3dhKeyBundleUploadRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

