/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Users } from './users';

/**
 * 
 * @export
 * @interface Contact
 */
export interface Contact {
    /**
     * 
     * @type {number}
     * @memberof Contact
     */
    'id'?: number;
    /**
     * 
     * @type {Users}
     * @memberof Contact
     */
    'user'?: Users;
    /**
     * 
     * @type {Users}
     * @memberof Contact
     */
    'contact'?: Users;
    /**
     * 
     * @type {boolean}
     * @memberof Contact
     */
    'blocked'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    'updatedAt'?: string;
}

