/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Users } from './users';

/**
 * 
 * @export
 * @interface UserRegisterRequest
 */
export interface UserRegisterRequest {
    /**
     * 
     * @type {Users}
     * @memberof UserRegisterRequest
     */
    'userData'?: Users;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterRequest
     */
    'publicKey': string;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterRequest
     */
    'identityPublicKey': string;
}

