/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserClientDto
 */
export interface UserClientDto {
    /**
     * 
     * @type {number}
     * @memberof UserClientDto
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserClientDto
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserClientDto
     */
    'email'?: string;
}

